In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

csv_file_path='top200_training.xls'
#記得pip install xlrd
df = pd.read_excel(csv_file_path)
#df.head()

In [15]:
from itertools import product
from itertools import combinations


# 將年月轉換為日期型數據
df['年月'] = pd.to_datetime(df['年月'], format='%Y%m')

# 獲取所有不同的年份
all_years = ['1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008']

# 開始的欄位
start_column = '1997'

# 開始欄位的索引
start_index = all_years.index(start_column)

# 創建一個字典來保存結果
year_combinations_dict = {}

# 生成所有可能的欄位組合
for i in range(1, len(all_years) - start_index + 1):
    for subset in combinations(all_years[start_index:], i):
        selected_columns = list(subset)
        # 將結果存入字典
        year_combinations_dict[len(year_combinations_dict) + 1] = selected_columns

# 打開一個檔案來保存結果
with open('year_combinations.txt', 'w') as file:
    # 遍歷字典，將結果寫入檔案
    for key, value in year_combinations_dict.items():
        file.write(f"Key: {key}, Selected year: {value}\n")
        # 在這裡進行你的分析或模型擬合等操作
        # ...
        file.write("\n" + "="*40 + "\n")

# 提示保存成功
print("Results saved to 'year_combinations.txt'")

Results saved to 'year_combinations.txt'


In [16]:
from itertools import combinations
from sklearn.model_selection import train_test_split
# 所有的欄位
all_columns = ['股價淨值比', '股價營收比' ,'M淨值報酬率─稅後', 'M營業利益成長率', 'M稅後淨利成長率']

# 開始的欄位
start_column = '股價淨值比'

# 開始欄位的索引
start_index = all_columns.index(start_column)

# 創建一個字典來保存結果
column_combinations_dict = {}

# 生成所有可能的欄位組合
for i in range(1, len(all_columns) - start_index + 1):
    for subset in combinations(all_columns[start_index:], i):
        selected_columns = list(subset)
        # 將結果存入字典
        column_combinations_dict[len(column_combinations_dict) + 1] = selected_columns

# 打開一個檔案來保存結果
with open('column_combinations_KNN_train.txt', 'w') as file:
    # 遍歷字典，將結果寫入檔案
    for key, value in column_combinations_dict.items():
        file.write(f"Key: {key}, Selected Columns: {value}\n")
        # 在這裡進行你的分析或模型擬合等操作
        # ...
        file.write("\n" + "="*40 + "\n")

# 提示保存成功
print("Results saved to 'column_combinations_KNN_train.txt'")


Results saved to 'column_combinations_KNN_train.txt'


In [ ]:
max_ret=0
ans={}
list_ans=[]
#選擇特定欄位分析
from sklearn.preprocessing import StandardScaler
from itertools import islice
cols=0
start_index = 1  # 第3001筆資料的索引
end_index = 4093  # 最後一筆資料的索引

selected_range = islice(year_combinations_dict.items(), start_index, end_index + 1)
#selected_range = islice(year_combinations_dict.items(), 4094) #4094是所有可用來訓練的年份組合

#16384
with open('KNN_train_test_result.txt', 'a') as file:
    for key, selected_years in selected_range:
        
        # 選擇訓練集年分
        train_years = [int(year) for year in selected_years]
        #print(train_years)

        #print("---------------------")
        # 選擇測試集年分
        test_years = [int(year) for year in all_years if year not in selected_years]
        print(f'總共有test year:{len(test_years)}')
        
        # 根據年份選擇訓練集
        train_data = df[df['年月'].dt.year.isin(train_years)]
        print(f"Number of rows in train_data: {len(train_data)}")
        #print(train_data)
        
        # 排除指定列，並標準化
        #columns_to_exclude = ['簡稱', '證券代碼', '年月', 'ReturnMean_year_Label', 'Return']
        #features_to_scale_train = train_data.drop(columns=columns_to_exclude)
        #features_to_scale_test = test_data.drop(columns=columns_to_exclude)
    
        for col in range (1,32):#取top10組合的前幾大frquency的屬性組合測試
            cols=cols+1
            list_ans=[]
            # 指定要選擇的欄位
            selected_columns = column_combinations_dict[col]
            list_ans.append(selected_columns)
            
            # 選擇指定的欄位
            features_to_scale_train = train_data[selected_columns]

            scaler = StandardScaler()
            scaled_features_train = scaler.fit_transform(features_to_scale_train)
            
            # 轉換為dataframe
            df_feat_train = pd.DataFrame(scaled_features_train, columns=features_to_scale_train.columns)
            
        #---------------------------------------------------------------------------------------------
            # 分割訓練集和測試集
            X_train = df_feat_train
            y_train = train_data['ReturnMean_year_Label']
            
            X_train, X_test, y_train, y_test = train_test_split(X_train,y_train,test_size=0.3,random_state=101)
  
        #--------------------------------------------------------------------------------------------------
            error_rate = []
            from sklearn.neighbors import KNeighborsClassifier
            for i in range(1, 100):
                knn = KNeighborsClassifier(n_neighbors=i, p=2, weights='distance', algorithm='brute')
                knn.fit(X_train, y_train)
                pred_i = knn.predict(X_test)
                error_rate.append(np.mean(pred_i != y_test))

            # 將k=1~60的錯誤率製圖畫出。k=23之後，錯誤率就在5-6%之間震盪。
            #plt.figure(figsize=(10, 6))
            #plt.plot(range(1, 100), error_rate, color='blue', linestyle='dashed', marker='o', markerfacecolor='red', markersize=10)
            #plt.title('Error Rate vs. K Value')
            #plt.xlabel('K')
            #plt.ylabel('Error Rate')
            #plt.show()
        #--------------------------------------------------------------------------------------------------
            min_error = min(error_rate)
            optimal_k = error_rate.index(min_error) + 1  # Adding 1 because Python indexing starts from 0

            print(f"Optimal k value for minimum error rate: {optimal_k}")
            #print(f"Minimum Error Rate: {min_error}")
            list_ans.append(optimal_k)
        #--------------------------------------------------------------------------------------------------
            #使用KNN演算法
            clf=KNeighborsClassifier(n_neighbors=optimal_k,p=2,weights='distance',algorithm='brute')
            clf.fit(X_train,y_train)
        #--------------------------------------------------------------------------------------------------
            predict_label1={}
            predict_k_pre5={}
        #--------------------------------------------------------------------------------------------------

            for year in test_years:
                
                # 選擇特定年份的 test_data
                test_data = df[df['年月'].dt.year == year]
                print(year)
                #print(test_data)
                print(f"Number of rows in test_data: {len(test_data)}")
                
                # 選擇指定的欄位
                features_to_scale_test = test_data[selected_columns]
                # 使用之前訓練好的標準化物件進行標準化
                scaled_features_test = scaler.transform(features_to_scale_test)
                # 將標準化後的特徵資料轉換為 DataFrame
                df_feat_test = pd.DataFrame(scaled_features_test, columns=features_to_scale_test.columns)

                
                # 使用已經訓練好的模型進行預測
                predictions_new = clf.predict(df_feat_test)

                #------------------------------
                #測試KNN演算法的好壞
                from sklearn.metrics import classification_report,confusion_matrix
                #將實際類別分為真正例（True Positive）、真負例（True Negative）、偽正例（False Positive）和偽負例（False Negative）
                print('confusion_matrix:')
                print(confusion_matrix(test_data['ReturnMean_year_Label'],predictions_new))

                #模型的精確度、召回率、F1分數和支持數等指標，用來評估模型對於每個類別的預測性能。
                print('classification_report')
                print(classification_report(test_data['ReturnMean_year_Label'],predictions_new))

                # 比較預測結果
                accuracy_new = clf.score(df_feat_test, test_data['ReturnMean_year_Label'])
                print(f'新數據的預測準確率: {accuracy_new}')
                #---------------------------------------
                #print(predictions_new)

                #predicted_positive_indices = (predictions_new == 1)

                # 獲取股票名稱
                #predicted_positive_stock_names = new.loc[predicted_positive_indices, '簡稱']

                # 設定檔案名稱
                #output_file_name = 'selected_stocks_1998.csv'

                # 匯出成 CSV 檔案
                #predicted_positive_stock_names.to_csv(output_file_name, index=True)

                # 預測要投資的股票名稱
                #print("選擇股票:")
                #print(predicted_positive_stock_names)


                # 選擇預測為1的股票
                selected_stocks = test_data[predictions_new == 1]

                # 計算return
                stock_returns = selected_stocks['Return']

                portfolio_returns = (stock_returns.mean()/100)+1

                print(portfolio_returns)
                predict_label1[year]=portfolio_returns

                # 使用 kneighbors 方法取得最近鄰居的索引和距離
                distances, indices = clf.kneighbors(df_feat_test, n_neighbors=5)

                # 合併所有測試樣本的最近鄰居索引
                all_indices = np.concatenate(indices)
                all_distances = np.concatenate(distances)

                # 將索引和距離組合成一個 2D 陣列，方便排序
                combined_data = np.column_stack((all_indices, all_distances))

                # 按照距離重新排序
                sorted_combined_data = combined_data[np.argsort(combined_data[:, 1])]

                # 選取最近鄰居中預測值為1的前5筆，且不重複
                selected_indices = set()
                i = 0
                while len(selected_indices) < 5 and i < len(sorted_combined_data):
                    index = int(sorted_combined_data[i, 0])
                    if(index>=200 and index<400):
                        index=index-200
                    elif(index>=400 and index<600):
                        index=index-400
                    elif(index>=600 and index<800):
                        index=index-600
                    elif(index>=800 and index<1000):
                        index=index-800
                    elif(index>=1000 and index<1200):
                        index=index-1000
                    elif(index>=1200 and index<1400):
                        index=index-1200
                    elif(index>=1400 and index<1600):
                        index=index-1400
                    elif(index>=1600 and index<1800):
                        index=index-1600
                    elif(index>=1800 and index<2000):
                        index=index-1800
                    elif(index>=2000 and index<2200):
                        index=index-2000
                    elif(index>=2200 and index<2400):
                        index=index-2200
                    elif(index>=2400 and index<2600):
                        index=index-2400
                    elif(index>=2600 and index<2800):
                        index=index-2600
                    elif(index>=2800 and index<3000):
                        index=index-2800
                    elif(index>=3000 and index<3200):
                        index=index-3000
                    prediction = predictions_new[index]
                    if prediction == 1 and index not in selected_indices:
                        selected_indices.add(index)
                    i += 1

                # 將選取的索引轉換成列表
                selected_indices_list = list(selected_indices)

                # 打印最近鄰居中預測值為1的前5筆索引
                print("最近鄰居中預測值為1的前5筆索引:")
                print(selected_indices_list)
                select = test_data
                # 獲取股票名稱
                selects_stock = select.iloc[selected_indices_list]['簡稱']
                print(selects_stock)
                # 獲取股票return
                selects_ret = select.iloc[selected_indices_list]['Return']
                print(selects_ret)
                with open(f'selected_stock_KNN_train/{cols}.txt', 'a') as stockfile:
                    stockfile.write(selects_stock.to_string())
                    stockfile.write('\n')
                    stockfile.write(selects_ret.to_string())
                # 計算return
                stock_returns = (selects_ret.mean() / 100)+1
                portfolio_returns = stock_returns
                print(portfolio_returns)
                predict_k_pre5[year] = portfolio_returns
                #print(stock_returns)
            sum1=1
            sum2=1
            print(predict_label1)
            for k in predict_label1.keys():
                if not (predict_label1[k]==0):
                    sum1=predict_label1[k]*sum1
            print(f'年均化複利為:{sum1/int(len(test_years))}')
            print('\n')
            print(predict_k_pre5)
            for k in predict_k_pre5.keys():
                if not (predict_k_pre5[k]==0):
                    sum2=predict_k_pre5[k]*sum2
            print(f'年均化複利為:{sum2/int(len(test_years))}')
            #list_ans.append(sum2/len(test_data)/200)
            print(f'ori sum2:{sum2}')
            print(f'test years have:{int(len(test_years))}')
            sum2=sum2/int(len(test_years))
            print(f'after sum2:{sum2}')
            list_ans.append(sum2)
            ans[cols]=list_ans
            file.write(f'{cols}:{list_ans}\n\n')
            file.flush()  # 強制將緩衝區內容寫入檔案
            if(sum2>max_ret):
                max_ret=sum2
                with open('max_KNN_train.txt', 'w') as maxfile:
                    maxfile.write(f'max:train_year:{train_years},test_year:{test_years}:{cols}:{list_ans}\n\n')
                    maxfile.flush()  # 強制將緩衝區內容寫入檔案

總共有test year:11
Number of rows in train_data: 200
Optimal k value for minimum error rate: 67
1998
Number of rows in test_data: 200
confusion_matrix:
[[69 57]
 [40 34]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.55      0.59       126
           1       0.37      0.46      0.41        74

    accuracy                           0.52       200
   macro avg       0.50      0.50      0.50       200
weighted avg       0.54      0.52      0.52       200

新數據的預測準確率: 0.515
1.1148766703296702
最近鄰居中預測值為1的前5筆索引:
[137, 74, 13, 46, 84]
337    云辰         
274    中工         
213    統一         
246     中石化       
284    永大         
Name: 簡稱, dtype: object
337    58.8567
274   -37.7753
213    -0.8643
246   -13.4566
284   -39.3594
Name: Return, dtype: float64
0.9348022
1999
Number of rows in test_data: 200
confusion_matrix:
[[77 34]
 [47 42]]
classification_report
              precision    recall  f1-score   support

          -1       0.6

2.5603743999999997
{1998: 1.1148766703296702, 1999: 0.6161642236842106, 2000: 1.3592645289256198, 2001: 1.0614596666666667, 2002: 1.3691212201010101, 2003: 1.0875387620689656, 2004: 1.1147295465753424, 2005: 1.404274577142857, 2006: 1.1688538295081967, 2007: 0.5427639230769231, 2008: 2.105020606382978}
年均化複利為:0.2804618679528036


{1998: 0.9348022, 1999: 0.4402458, 2000: 0.9475709999999999, 2001: 0.9146118, 2002: 1.1204276, 2003: 0.94518866, 2004: 0.9563232, 2005: 1.5150481999999998, 2006: 1.1342576, 2007: 0.4794286, 2008: 2.5603743999999997}
年均化複利為:0.06926971132156413
ori sum2:0.7619668245372055
test years have:11
after sum2:0.06926971132156413
Optimal k value for minimum error rate: 9
1998
Number of rows in test_data: 200
confusion_matrix:
[[67 59]
 [31 43]]
classification_report
              precision    recall  f1-score   support

          -1       0.68      0.53      0.60       126
           1       0.42      0.58      0.49        74

    accuracy                           0.55 

Optimal k value for minimum error rate: 7
1998
Number of rows in test_data: 200
confusion_matrix:
[[88 38]
 [36 38]]
classification_report
              precision    recall  f1-score   support

          -1       0.71      0.70      0.70       126
           1       0.50      0.51      0.51        74

    accuracy                           0.63       200
   macro avg       0.60      0.61      0.61       200
weighted avg       0.63      0.63      0.63       200

新數據的預測準確率: 0.63
1.2076406315789474
最近鄰居中預測值為1的前5筆索引:
[97, 3, 70, 84, 21]
297    國聯         
203    中鋼         
270    大陸         
284    永大         
221    華宇         
Name: 簡稱, dtype: object
297   -21.2843
203    39.6414
270   -21.0983
284   -39.3594
221    23.9331
Name: Return, dtype: float64
0.963665
1999
Number of rows in test_data: 200
confusion_matrix:
[[74 37]
 [46 43]]
classification_report
              precision    recall  f1-score   support

          -1       0.62      0.67      0.64       111
           1       0.54

Optimal k value for minimum error rate: 21
1998
Number of rows in test_data: 200
confusion_matrix:
[[81 45]
 [52 22]]
classification_report
              precision    recall  f1-score   support

          -1       0.61      0.64      0.63       126
           1       0.33      0.30      0.31        74

    accuracy                           0.52       200
   macro avg       0.47      0.47      0.47       200
weighted avg       0.51      0.52      0.51       200

新數據的預測準確率: 0.515
1.032706223880597
最近鄰居中預測值為1的前5筆索引:
[101, 71, 105, 47, 95]
301    大榮         
271    燿華         
305    巨大         
247    台鳳         
295    長億         
Name: 簡稱, dtype: object
301   -52.4020
271   -24.7732
305   -41.9580
247   -54.5685
295   -33.8082
Name: Return, dtype: float64
0.5849802
1999
Number of rows in test_data: 200
confusion_matrix:
[[76 35]
 [58 31]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.68      0.62       111
           1      

Optimal k value for minimum error rate: 45
1998
Number of rows in test_data: 200
confusion_matrix:
[[85 41]
 [47 27]]
classification_report
              precision    recall  f1-score   support

          -1       0.64      0.67      0.66       126
           1       0.40      0.36      0.38        74

    accuracy                           0.56       200
   macro avg       0.52      0.52      0.52       200
weighted avg       0.55      0.56      0.56       200

新數據的預測準確率: 0.56
1.141477411764706
最近鄰居中預測值為1的前5筆索引:
[0, 99, 35, 10, 13]
200     台積電       
299     三商行       
235    大眾         
210    華通         
213    統一         
Name: 簡稱, dtype: object
200    193.2025
299     10.7232
235      5.6047
210      5.8307
213     -0.8643
Name: Return, dtype: float64
1.4289936
1999
Number of rows in test_data: 200
confusion_matrix:
[[76 35]
 [57 32]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.68      0.62       111
           1     

Optimal k value for minimum error rate: 37
1998
Number of rows in test_data: 200
confusion_matrix:
[[81 45]
 [45 29]]
classification_report
              precision    recall  f1-score   support

          -1       0.64      0.64      0.64       126
           1       0.39      0.39      0.39        74

    accuracy                           0.55       200
   macro avg       0.52      0.52      0.52       200
weighted avg       0.55      0.55      0.55       200

新數據的預測準確率: 0.55
1.1502462162162161
最近鄰居中預測值為1的前5筆索引:
[42, 108, 23, 120, 126]
242    環電         
308    和桐         
223    長榮         
320    智邦         
326    德寶         
Name: 簡稱, dtype: object
242     47.7528
308    -11.8421
223     -1.1512
320    153.0937
326    -45.1830
Name: Return, dtype: float64
1.2853404
1999
Number of rows in test_data: 200
confusion_matrix:
[[84 27]
 [47 42]]
classification_report
              precision    recall  f1-score   support

          -1       0.64      0.76      0.69       111
           1

Optimal k value for minimum error rate: 29
1998
Number of rows in test_data: 200
confusion_matrix:
[[89 37]
 [38 36]]
classification_report
              precision    recall  f1-score   support

          -1       0.70      0.71      0.70       126
           1       0.49      0.49      0.49        74

    accuracy                           0.62       200
   macro avg       0.60      0.60      0.60       200
weighted avg       0.62      0.62      0.62       200

新數據的預測準確率: 0.625
1.230245794520548
最近鄰居中預測值為1的前5筆索引:
[72, 105, 10, 19, 121]
272    微星         
305    巨大         
210    華通         
219    亞泥         
321    致茂         
Name: 簡稱, dtype: object
272    81.6998
305   -41.9580
210     5.8307
219     3.2937
321    41.9126
Name: Return, dtype: float64
1.1815576
1999
Number of rows in test_data: 200
confusion_matrix:
[[81 30]
 [50 39]]
classification_report
              precision    recall  f1-score   support

          -1       0.62      0.73      0.67       111
           1      

Optimal k value for minimum error rate: 18
1998
Number of rows in test_data: 200
confusion_matrix:
[[58 68]
 [41 33]]
classification_report
              precision    recall  f1-score   support

          -1       0.59      0.46      0.52       126
           1       0.33      0.45      0.38        74

    accuracy                           0.46       200
   macro avg       0.46      0.45      0.45       200
weighted avg       0.49      0.46      0.46       200

新數據的預測準確率: 0.455
1.0776122574257425
最近鄰居中預測值為1的前5筆索引:
[66, 105, 109, 82, 19]
266    士電         
305    巨大         
309    聯華         
282     永豐餘       
219    亞泥         
Name: 簡稱, dtype: object
266   -28.3646
305   -41.9580
309   -19.8123
282     1.6313
219     3.2937
Name: Return, dtype: float64
0.8295802
1999
Number of rows in test_data: 200
confusion_matrix:
[[77 34]
 [43 46]]
classification_report
              precision    recall  f1-score   support

          -1       0.64      0.69      0.67       111
           1     

Optimal k value for minimum error rate: 64
1998
Number of rows in test_data: 200
confusion_matrix:
[[79 47]
 [52 22]]
classification_report
              precision    recall  f1-score   support

          -1       0.60      0.63      0.61       126
           1       0.32      0.30      0.31        74

    accuracy                           0.51       200
   macro avg       0.46      0.46      0.46       200
weighted avg       0.50      0.51      0.50       200

新數據的預測準確率: 0.505
1.078334043478261
最近鄰居中預測值為1的前5筆索引:
[99, 73, 109, 28, 126]
299     三商行       
273    遠百         
309    聯華         
228    中環         
326    德寶         
Name: 簡稱, dtype: object
299     10.7232
273    -26.2729
309    -19.8123
228    191.6759
326    -45.1830
Name: Return, dtype: float64
1.2222618
1999
Number of rows in test_data: 200
confusion_matrix:
[[84 27]
 [50 39]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.76      0.69       111
           1 

Optimal k value for minimum error rate: 10
1998
Number of rows in test_data: 200
confusion_matrix:
[[90 36]
 [37 37]]
classification_report
              precision    recall  f1-score   support

          -1       0.71      0.71      0.71       126
           1       0.51      0.50      0.50        74

    accuracy                           0.64       200
   macro avg       0.61      0.61      0.61       200
weighted avg       0.63      0.64      0.63       200

新數據的預測準確率: 0.635
1.2287690273972602
最近鄰居中預測值為1的前5筆索引:
[6, 71, 73, 11, 121]
206     英業達       
271    燿華         
273    遠百         
211    仁寶         
321    致茂         
Name: 簡稱, dtype: object
206   -13.1390
271   -24.7732
273   -26.2729
211    39.4893
321    41.9126
Name: Return, dtype: float64
1.0344336
1999
Number of rows in test_data: 200
confusion_matrix:
[[79 32]
 [50 39]]
classification_report
              precision    recall  f1-score   support

          -1       0.61      0.71      0.66       111
           1       

Optimal k value for minimum error rate: 16
1998
Number of rows in test_data: 200
confusion_matrix:
[[70 56]
 [40 34]]
classification_report
              precision    recall  f1-score   support

          -1       0.64      0.56      0.59       126
           1       0.38      0.46      0.41        74

    accuracy                           0.52       200
   macro avg       0.51      0.51      0.50       200
weighted avg       0.54      0.52      0.53       200

新數據的預測準確率: 0.52
1.1176485333333332
最近鄰居中預測值為1的前5筆索引:
[9, 13, 20, 91, 125]
209    宏電         
213    統一         
220    台泥         
291    國產         
325    精英         
Name: 簡稱, dtype: object
209    191.3663
213     -0.8643
220     30.3519
291    -24.1580
325     80.1532
Name: Return, dtype: float64
1.5536982
1999
Number of rows in test_data: 200
confusion_matrix:
[[70 41]
 [40 49]]
classification_report
              precision    recall  f1-score   support

          -1       0.64      0.63      0.63       111
           1   

Optimal k value for minimum error rate: 48
1998
Number of rows in test_data: 200
confusion_matrix:
[[89 37]
 [41 33]]
classification_report
              precision    recall  f1-score   support

          -1       0.68      0.71      0.70       126
           1       0.47      0.45      0.46        74

    accuracy                           0.61       200
   macro avg       0.58      0.58      0.58       200
weighted avg       0.61      0.61      0.61       200

新數據的預測準確率: 0.61
1.2116958714285713
最近鄰居中預測值為1的前5筆索引:
[9, 13, 19, 117, 125]
209    宏電         
213    統一         
219    亞泥         
317    東陽         
325    精英         
Name: 簡稱, dtype: object
209    191.3663
213     -0.8643
219      3.2937
317    -24.1624
325     80.1532
Name: Return, dtype: float64
1.499573
1999
Number of rows in test_data: 200
confusion_matrix:
[[78 33]
 [47 42]]
classification_report
              precision    recall  f1-score   support

          -1       0.62      0.70      0.66       111
           1   

Optimal k value for minimum error rate: 16
1998
Number of rows in test_data: 200
confusion_matrix:
[[81 45]
 [41 33]]
classification_report
              precision    recall  f1-score   support

          -1       0.66      0.64      0.65       126
           1       0.42      0.45      0.43        74

    accuracy                           0.57       200
   macro avg       0.54      0.54      0.54       200
weighted avg       0.57      0.57      0.57       200

新數據的預測準確率: 0.57
1.1469741282051282
最近鄰居中預測值為1的前5筆索引:
[97, 68, 9, 13, 122]
297    國聯         
268    中鼎         
209    宏電         
213    統一         
322    建大         
Name: 簡稱, dtype: object
297    -21.2843
268    -43.5616
209    191.3663
213     -0.8643
322    -26.7635
Name: Return, dtype: float64
1.1977852
1999
Number of rows in test_data: 200
confusion_matrix:
[[72 39]
 [43 46]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.65      0.64       111
           1   

Optimal k value for minimum error rate: 95
1998
Number of rows in test_data: 200
confusion_matrix:
[[95 31]
 [45 29]]
classification_report
              precision    recall  f1-score   support

          -1       0.68      0.75      0.71       126
           1       0.48      0.39      0.43        74

    accuracy                           0.62       200
   macro avg       0.58      0.57      0.57       200
weighted avg       0.61      0.62      0.61       200

新數據的預測準確率: 0.62
1.22489895
最近鄰居中預測值為1的前5筆索引:
[68, 8, 77, 21, 62]
268    中鼎         
208     華邦電       
277     金像電       
221    華宇         
262    宏盛         
Name: 簡稱, dtype: object
268    -43.5616
208    118.4988
277     -8.0565
221     23.9331
262    -24.7914
Name: Return, dtype: float64
1.1320448
1999
Number of rows in test_data: 200
confusion_matrix:
[[86 25]
 [55 34]]
classification_report
              precision    recall  f1-score   support

          -1       0.61      0.77      0.68       111
           1       0.58 

Optimal k value for minimum error rate: 88
1998
Number of rows in test_data: 200
confusion_matrix:
[[102  24]
 [ 63  11]]
classification_report
              precision    recall  f1-score   support

          -1       0.62      0.81      0.70       126
           1       0.31      0.15      0.20        74

    accuracy                           0.56       200
   macro avg       0.47      0.48      0.45       200
weighted avg       0.51      0.56      0.52       200

新數據的預測準確率: 0.565
1.0960566571428572
最近鄰居中預測值為1的前5筆索引:
[66, 35, 43, 23, 61]
266    士電         
235    大眾         
243    正新         
223    長榮         
261    中保         
Name: 簡稱, dtype: object
266   -28.3646
235     5.6047
243   -22.2567
223    -1.1512
261    64.3736
Name: Return, dtype: float64
1.0364116
1999
Number of rows in test_data: 200
confusion_matrix:
[[87 24]
 [68 21]]
classification_report
              precision    recall  f1-score   support

          -1       0.56      0.78      0.65       111
           1   

Optimal k value for minimum error rate: 15
1998
Number of rows in test_data: 200
confusion_matrix:
[[86 40]
 [36 38]]
classification_report
              precision    recall  f1-score   support

          -1       0.70      0.68      0.69       126
           1       0.49      0.51      0.50        74

    accuracy                           0.62       200
   macro avg       0.60      0.60      0.60       200
weighted avg       0.62      0.62      0.62       200

新數據的預測準確率: 0.62
1.2802746025641025
最近鄰居中預測值為1的前5筆索引:
[99, 135, 72, 39, 52]
299     三商行       
335    敬鵬         
272    微星         
239    神達         
252    友訊         
Name: 簡稱, dtype: object
299    10.7232
335    -2.5884
272    81.6998
239    22.0115
252     2.0018
Name: Return, dtype: float64
1.2276958
1999
Number of rows in test_data: 200
confusion_matrix:
[[84 27]
 [50 39]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.76      0.69       111
           1       

Optimal k value for minimum error rate: 5
1998
Number of rows in test_data: 200
confusion_matrix:
[[70 56]
 [41 33]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.56      0.59       126
           1       0.37      0.45      0.40        74

    accuracy                           0.52       200
   macro avg       0.50      0.50      0.50       200
weighted avg       0.53      0.52      0.52       200

新數據的預測準確率: 0.515
1.1510054943820225
最近鄰居中預測值為1的前5筆索引:
[72, 51, 19, 23, 126]
272    微星         
251    矽統         
219    亞泥         
223    長榮         
326    德寶         
Name: 簡稱, dtype: object
272     81.6998
251    154.6171
219      3.2937
223     -1.1512
326    -45.1830
Name: Return, dtype: float64
1.3865528
1999
Number of rows in test_data: 200
confusion_matrix:
[[76 35]
 [41 48]]
classification_report
              precision    recall  f1-score   support

          -1       0.65      0.68      0.67       111
           1  

Optimal k value for minimum error rate: 59
1998
Number of rows in test_data: 200
confusion_matrix:
[[82 44]
 [45 29]]
classification_report
              precision    recall  f1-score   support

          -1       0.65      0.65      0.65       126
           1       0.40      0.39      0.39        74

    accuracy                           0.56       200
   macro avg       0.52      0.52      0.52       200
weighted avg       0.55      0.56      0.55       200

新數據的預測準確率: 0.555
1.1259396712328766
最近鄰居中預測值為1的前5筆索引:
[105, 11, 117, 24, 63]
305    巨大         
211    仁寶         
317    東陽         
224    寶成         
263     統一實       
Name: 簡稱, dtype: object
305   -41.9580
211    39.4893
317   -24.1624
224    25.5390
263   -32.4153
Name: Return, dtype: float64
0.9329852
1999
Number of rows in test_data: 200
confusion_matrix:
[[80 31]
 [42 47]]
classification_report
              precision    recall  f1-score   support

          -1       0.66      0.72      0.69       111
           1     

Optimal k value for minimum error rate: 17
1998
Number of rows in test_data: 200
confusion_matrix:
[[89 37]
 [36 38]]
classification_report
              precision    recall  f1-score   support

          -1       0.71      0.71      0.71       126
           1       0.51      0.51      0.51        74

    accuracy                           0.64       200
   macro avg       0.61      0.61      0.61       200
weighted avg       0.64      0.64      0.64       200

新數據的預測準確率: 0.635
1.2854568933333332
最近鄰居中預測值為1的前5筆索引:
[72, 105, 19, 120, 26]
272    微星         
305    巨大         
219    亞泥         
320    智邦         
226     統一超       
Name: 簡稱, dtype: object
272     81.6998
305    -41.9580
219      3.2937
320    153.0937
226     62.5085
Name: Return, dtype: float64
1.5172754
1999
Number of rows in test_data: 200
confusion_matrix:
[[81 30]
 [49 40]]
classification_report
              precision    recall  f1-score   support

          -1       0.62      0.73      0.67       111
           1

Optimal k value for minimum error rate: 14
1998
Number of rows in test_data: 200
confusion_matrix:
[[77 49]
 [39 35]]
classification_report
              precision    recall  f1-score   support

          -1       0.66      0.61      0.64       126
           1       0.42      0.47      0.44        74

    accuracy                           0.56       200
   macro avg       0.54      0.54      0.54       200
weighted avg       0.57      0.56      0.56       200

新數據的預測準確率: 0.56
1.1248894285714286
最近鄰居中預測值為1的前5筆索引:
[66, 19, 52, 24, 60]
266    士電         
219    亞泥         
252    友訊         
224    寶成         
260    飛瑞         
Name: 簡稱, dtype: object
266   -28.3646
219     3.2937
252     2.0018
224    25.5390
260    11.1953
Name: Return, dtype: float64
1.0273304
1999
Number of rows in test_data: 200
confusion_matrix:
[[79 32]
 [43 46]]
classification_report
              precision    recall  f1-score   support

          -1       0.65      0.71      0.68       111
           1       0

Optimal k value for minimum error rate: 8
1998
Number of rows in test_data: 200
confusion_matrix:
[[71 55]
 [41 33]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.56      0.60       126
           1       0.38      0.45      0.41        74

    accuracy                           0.52       200
   macro avg       0.50      0.50      0.50       200
weighted avg       0.54      0.52      0.53       200

新數據的預測準確率: 0.52
1.1391906818181818
最近鄰居中預測值為1的前5筆索引:
[136, 73, 109, 88, 60]
336    裕民         
273    遠百         
309    聯華         
288    永信         
260    飛瑞         
Name: 簡稱, dtype: object
336   -11.1940
273   -26.2729
309   -19.8123
288   -52.5440
260    11.1953
Name: Return, dtype: float64
0.8027442
1999
Number of rows in test_data: 200
confusion_matrix:
[[68 43]
 [41 48]]
classification_report
              precision    recall  f1-score   support

          -1       0.62      0.61      0.62       111
           1       

Optimal k value for minimum error rate: 13
1998
Number of rows in test_data: 200
confusion_matrix:
[[87 39]
 [34 40]]
classification_report
              precision    recall  f1-score   support

          -1       0.72      0.69      0.70       126
           1       0.51      0.54      0.52        74

    accuracy                           0.64       200
   macro avg       0.61      0.62      0.61       200
weighted avg       0.64      0.64      0.64       200

新數據的預測準確率: 0.635
1.2431835569620253
最近鄰居中預測值為1的前5筆索引:
[99, 6, 71, 11, 13]
299     三商行       
206     英業達       
271    燿華         
211    仁寶         
213    統一         
Name: 簡稱, dtype: object
299    10.7232
206   -13.1390
271   -24.7732
211    39.4893
213    -0.8643
Name: Return, dtype: float64
1.022872
1999
Number of rows in test_data: 200
confusion_matrix:
[[75 36]
 [44 45]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.68      0.65       111
           1       0.

Optimal k value for minimum error rate: 97
1998
Number of rows in test_data: 200
confusion_matrix:
[[97 29]
 [44 30]]
classification_report
              precision    recall  f1-score   support

          -1       0.69      0.77      0.73       126
           1       0.51      0.41      0.45        74

    accuracy                           0.64       200
   macro avg       0.60      0.59      0.59       200
weighted avg       0.62      0.64      0.62       200

新數據的預測準確率: 0.635
1.2359585762711864
最近鄰居中預測值為1的前5筆索引:
[135, 77, 17, 24, 121]
335    敬鵬         
277     金像電       
217     台達電       
224    寶成         
321    致茂         
Name: 簡稱, dtype: object
335    -2.5884
277    -8.0565
217    61.8932
224    25.5390
321    41.9126
Name: Return, dtype: float64
1.2373998
1999
Number of rows in test_data: 200
confusion_matrix:
[[89 22]
 [61 28]]
classification_report
              precision    recall  f1-score   support

          -1       0.59      0.80      0.68       111
           1     

Optimal k value for minimum error rate: 18
1998
Number of rows in test_data: 200
confusion_matrix:
[[80 46]
 [40 34]]
classification_report
              precision    recall  f1-score   support

          -1       0.67      0.63      0.65       126
           1       0.42      0.46      0.44        74

    accuracy                           0.57       200
   macro avg       0.55      0.55      0.55       200
weighted avg       0.58      0.57      0.57       200

新數據的預測準確率: 0.57
1.166388
最近鄰居中預測值為1的前5筆索引:
[66, 109, 19, 60, 125]
266    士電         
309    聯華         
219    亞泥         
260    飛瑞         
325    精英         
Name: 簡稱, dtype: object
266   -28.3646
309   -19.8123
219     3.2937
260    11.1953
325    80.1532
Name: Return, dtype: float64
1.0929306
1999
Number of rows in test_data: 200
confusion_matrix:
[[69 42]
 [47 42]]
classification_report
              precision    recall  f1-score   support

          -1       0.59      0.62      0.61       111
           1       0.50     

Optimal k value for minimum error rate: 94
1998
Number of rows in test_data: 200
confusion_matrix:
[[99 27]
 [48 26]]
classification_report
              precision    recall  f1-score   support

          -1       0.67      0.79      0.73       126
           1       0.49      0.35      0.41        74

    accuracy                           0.62       200
   macro avg       0.58      0.57      0.57       200
weighted avg       0.61      0.62      0.61       200

新數據的預測準確率: 0.625
1.2368602641509434
最近鄰居中預測值為1的前5筆索引:
[68, 5, 77, 49, 21]
268    中鼎         
205    鴻海         
277     金像電       
249    凌陽         
221    華宇         
Name: 簡稱, dtype: object
268   -43.5616
205    87.7049
277    -8.0565
249    80.2007
221    23.9331
Name: Return, dtype: float64
1.2804412
1999
Number of rows in test_data: 200
confusion_matrix:
[[87 24]
 [57 32]]
classification_report
              precision    recall  f1-score   support

          -1       0.60      0.78      0.68       111
           1       0

Optimal k value for minimum error rate: 11
1998
Number of rows in test_data: 200
confusion_matrix:
[[82 44]
 [35 39]]
classification_report
              precision    recall  f1-score   support

          -1       0.70      0.65      0.67       126
           1       0.47      0.53      0.50        74

    accuracy                           0.60       200
   macro avg       0.59      0.59      0.59       200
weighted avg       0.62      0.60      0.61       200

新數據的預測準確率: 0.605
1.2499892409638553
最近鄰居中預測值為1的前5筆索引:
[99, 39, 72, 52, 120]
299     三商行       
239    神達         
272    微星         
252    友訊         
320    智邦         
Name: 簡稱, dtype: object
299     10.7232
239     22.0115
272     81.6998
252      2.0018
320    153.0937
Name: Return, dtype: float64
1.53906
1999
Number of rows in test_data: 200
confusion_matrix:
[[82 29]
 [48 41]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.74      0.68       111
           1   

Optimal k value for minimum error rate: 6
1998
Number of rows in test_data: 200
confusion_matrix:
[[71 55]
 [41 33]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.56      0.60       126
           1       0.38      0.45      0.41        74

    accuracy                           0.52       200
   macro avg       0.50      0.50      0.50       200
weighted avg       0.54      0.52      0.53       200

新數據的預測準確率: 0.52
1.1139628181818182
最近鄰居中預測值為1的前5筆索引:
[7, 103, 73, 43, 24]
207     日月光       
303    耀文         
273    遠百         
243    正新         
224    寶成         
Name: 簡稱, dtype: object
207    130.6472
303    -39.2704
273    -26.2729
243    -22.2567
224     25.5390
Name: Return, dtype: float64
1.1367724
1999
Number of rows in test_data: 200
confusion_matrix:
[[73 38]
 [47 42]]
classification_report
              precision    recall  f1-score   support

          -1       0.61      0.66      0.63       111
           1    

Optimal k value for minimum error rate: 41
1998
Number of rows in test_data: 200
confusion_matrix:
[[71 55]
 [38 36]]
classification_report
              precision    recall  f1-score   support

          -1       0.65      0.56      0.60       126
           1       0.40      0.49      0.44        74

    accuracy                           0.54       200
   macro avg       0.52      0.52      0.52       200
weighted avg       0.56      0.54      0.54       200

新數據的預測準確率: 0.535
1.11534
最近鄰居中預測值為1的前5筆索引:
[109, 46, 117, 24, 126]
309    聯華         
246     中石化       
317    東陽         
224    寶成         
326    德寶         
Name: 簡稱, dtype: object
309   -19.8123
246   -13.4566
317   -24.1624
224    25.5390
326   -45.1830
Name: Return, dtype: float64
0.8458494
1999
Number of rows in test_data: 200
confusion_matrix:
[[72 39]
 [42 47]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.65      0.64       111
           1       0.55    

Optimal k value for minimum error rate: 15
1998
Number of rows in test_data: 200
confusion_matrix:
[[76 50]
 [39 35]]
classification_report
              precision    recall  f1-score   support

          -1       0.66      0.60      0.63       126
           1       0.41      0.47      0.44        74

    accuracy                           0.56       200
   macro avg       0.54      0.54      0.54       200
weighted avg       0.57      0.56      0.56       200

新數據的預測準確率: 0.555
1.1223876
最近鄰居中預測值為1的前5筆索引:
[66, 10, 19, 24, 60]
266    士電         
210    華通         
219    亞泥         
224    寶成         
260    飛瑞         
Name: 簡稱, dtype: object
266   -28.3646
210     5.8307
219     3.2937
224    25.5390
260    11.1953
Name: Return, dtype: float64
1.0349882
1999
Number of rows in test_data: 200
confusion_matrix:
[[79 32]
 [44 45]]
classification_report
              precision    recall  f1-score   support

          -1       0.64      0.71      0.68       111
           1       0.58     

Optimal k value for minimum error rate: 95
1998
Number of rows in test_data: 200
confusion_matrix:
[[97 29]
 [44 30]]
classification_report
              precision    recall  f1-score   support

          -1       0.69      0.77      0.73       126
           1       0.51      0.41      0.45        74

    accuracy                           0.64       200
   macro avg       0.60      0.59      0.59       200
weighted avg       0.62      0.64      0.62       200

新數據的預測準確率: 0.635
1.2359585762711864
最近鄰居中預測值為1的前5筆索引:
[135, 77, 17, 24, 121]
335    敬鵬         
277     金像電       
217     台達電       
224    寶成         
321    致茂         
Name: 簡稱, dtype: object
335    -2.5884
277    -8.0565
217    61.8932
224    25.5390
321    41.9126
Name: Return, dtype: float64
1.2373998
1999
Number of rows in test_data: 200
confusion_matrix:
[[89 22]
 [62 27]]
classification_report
              precision    recall  f1-score   support

          -1       0.59      0.80      0.68       111
           1     

Optimal k value for minimum error rate: 15
1998
Number of rows in test_data: 200
confusion_matrix:
[[80 46]
 [35 39]]
classification_report
              precision    recall  f1-score   support

          -1       0.70      0.63      0.66       126
           1       0.46      0.53      0.49        74

    accuracy                           0.59       200
   macro avg       0.58      0.58      0.58       200
weighted avg       0.61      0.59      0.60       200

新數據的預測準確率: 0.595
1.190058011764706
最近鄰居中預測值為1的前5筆索引:
[4, 7, 10, 24, 60]
204    台塑         
207     日月光       
210    華通         
224    寶成         
260    飛瑞         
Name: 簡稱, dtype: object
204     46.8071
207    130.6472
210      5.8307
224     25.5390
260     11.1953
Name: Return, dtype: float64
1.4400386
1999
Number of rows in test_data: 200
confusion_matrix:
[[76 35]
 [47 42]]
classification_report
              precision    recall  f1-score   support

          -1       0.62      0.68      0.65       111
           1     

Optimal k value for minimum error rate: 4
1997
Number of rows in test_data: 200
confusion_matrix:
[[68 41]
 [67 24]]
classification_report
              precision    recall  f1-score   support

          -1       0.50      0.62      0.56       109
           1       0.37      0.26      0.31        91

    accuracy                           0.46       200
   macro avg       0.44      0.44      0.43       200
weighted avg       0.44      0.46      0.44       200

新數據的預測準確率: 0.46
0.7801323692307692
最近鄰居中預測值為1的前5筆索引:
[7, 76, 118, 88, 91]
7      大同         
76     飛瑞         
118    友訊         
88     中強         
91     立榮         
Name: 簡稱, dtype: object
7       1.5517
76      6.8826
118    51.1769
88    -15.2596
91    -25.2783
Name: Return, dtype: float64
1.0381466
1999
Number of rows in test_data: 200
confusion_matrix:
[[86 25]
 [59 30]]
classification_report
              precision    recall  f1-score   support

          -1       0.59      0.77      0.67       111
           1       0.

Optimal k value for minimum error rate: 3
1997
Number of rows in test_data: 200
confusion_matrix:
[[79 30]
 [60 31]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.72      0.64       109
           1       0.51      0.34      0.41        91

    accuracy                           0.55       200
   macro avg       0.54      0.53      0.52       200
weighted avg       0.54      0.55      0.53       200

新數據的預測準確率: 0.55
0.8537656557377049
最近鄰居中預測值為1的前5筆索引:
[2, 13, 14, 51, 55]
2     中鋼         
13     華邦電       
14    裕隆         
51    聯強         
55     震旦行       
Name: 簡稱, dtype: object
2     -9.2224
13    11.5279
14     1.1003
51    46.0888
55   -16.1681
Name: Return, dtype: float64
1.066653
1999
Number of rows in test_data: 200
confusion_matrix:
[[80 31]
 [58 31]]
classification_report
              precision    recall  f1-score   support

          -1       0.58      0.72      0.64       111
           1       0.50      0.35

Optimal k value for minimum error rate: 62
1997
Number of rows in test_data: 200
confusion_matrix:
[[103   6]
 [ 65  26]]
classification_report
              precision    recall  f1-score   support

          -1       0.61      0.94      0.74       109
           1       0.81      0.29      0.42        91

    accuracy                           0.65       200
   macro avg       0.71      0.62      0.58       200
weighted avg       0.70      0.65      0.60       200

新數據的預測準確率: 0.645
0.9865985625
最近鄰居中預測值為1的前5筆索引:
[34, 107, 76, 109, 60]
34     中環         
107    光磊         
76     飛瑞         
109     楠梓電       
60     環電         
Name: 簡稱, dtype: object
34     25.1898
107   -12.7740
76      6.8826
109    62.2231
60     -4.7036
Name: Return, dtype: float64
1.1536358
1999
Number of rows in test_data: 200
confusion_matrix:
[[90 21]
 [69 20]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.81      0.67       111
           1       

Optimal k value for minimum error rate: 9
1997
Number of rows in test_data: 200
confusion_matrix:
[[88 21]
 [76 15]]
classification_report
              precision    recall  f1-score   support

          -1       0.54      0.81      0.64       109
           1       0.42      0.16      0.24        91

    accuracy                           0.52       200
   macro avg       0.48      0.49      0.44       200
weighted avg       0.48      0.52      0.46       200

新數據的預測準確率: 0.515
0.7977638333333333
最近鄰居中預測值為1的前5筆索引:
[96, 133, 14, 82, 125]
96     中化         
133    台紙         
14     裕隆         
82     冠德         
125    桂宏         
Name: 簡稱, dtype: object
96    -69.3471
133   -40.7609
14      1.1003
82    -35.4419
125   -35.0797
Name: Return, dtype: float64
0.6409414
1999
Number of rows in test_data: 200
confusion_matrix:
[[82 29]
 [76 13]]
classification_report
              precision    recall  f1-score   support

          -1       0.52      0.74      0.61       111
           1      

Optimal k value for minimum error rate: 26
1997
Number of rows in test_data: 200
confusion_matrix:
[[88 21]
 [73 18]]
classification_report
              precision    recall  f1-score   support

          -1       0.55      0.81      0.65       109
           1       0.46      0.20      0.28        91

    accuracy                           0.53       200
   macro avg       0.50      0.50      0.46       200
weighted avg       0.51      0.53      0.48       200

新數據的預測準確率: 0.53
0.7548604871794872
最近鄰居中預測值為1的前5筆索引:
[2, 104, 11, 111, 60]
2      中鋼         
104    聯華         
11     茂矽         
111    燁輝         
60     環電         
Name: 簡稱, dtype: object
2      -9.2224
104   -13.6036
11    -10.8920
111   -27.8249
60     -4.7036
Name: Return, dtype: float64
0.867507
1999
Number of rows in test_data: 200
confusion_matrix:
[[90 21]
 [75 14]]
classification_report
              precision    recall  f1-score   support

          -1       0.55      0.81      0.65       111
           1       0

Optimal k value for minimum error rate: 19
1997
Number of rows in test_data: 200
confusion_matrix:
[[89 20]
 [78 13]]
classification_report
              precision    recall  f1-score   support

          -1       0.53      0.82      0.64       109
           1       0.39      0.14      0.21        91

    accuracy                           0.51       200
   macro avg       0.46      0.48      0.43       200
weighted avg       0.47      0.51      0.45       200

新數據的預測準確率: 0.51
0.8353876666666666
最近鄰居中預測值為1的前5筆索引:
[0, 33, 134, 82, 124]
0       台積電       
33      統一超       
134    永光         
82     冠德         
124    力麗         
Name: 簡稱, dtype: object
0      -6.3648
33     24.9683
134   -23.2323
82    -35.4419
124   -38.5344
Name: Return, dtype: float64
0.8427898
1999
Number of rows in test_data: 200
confusion_matrix:
[[102   9]
 [ 80   9]]
classification_report
              precision    recall  f1-score   support

          -1       0.56      0.92      0.70       111
           1   

1.9983646000000002
{1997: 0.8353876666666666, 1999: 0.5032156666666666, 2000: 1.3392024999999999, 2001: 0.9216826952380952, 2002: 1.328738013888889, 2003: 0.9216472857142857, 2004: 1.0503281944444445, 2005: 1.117067484516129, 2006: 0.9852359166666667, 2007: 0.5022222424242424, 2008: 2.1298431562499998}
年均化複利為:0.07142817539411511


{1997: 0.8427898, 1999: 0.49987459999999995, 2000: 1.3268632, 2001: 0.85864732, 2002: 1.2632023000000001, 2003: 0.8263076, 2004: 0.8728130000000001, 2005: 1.0507026, 2006: 1.0131766, 2007: 0.5069868, 2008: 1.9983646000000002}
年均化複利為:0.04287467314529238
ori sum2:0.47162140459821617
test years have:11
after sum2:0.04287467314529238
Optimal k value for minimum error rate: 11
1997
Number of rows in test_data: 200
confusion_matrix:
[[95 14]
 [62 29]]
classification_report
              precision    recall  f1-score   support

          -1       0.61      0.87      0.71       109
           1       0.67      0.32      0.43        91

    accuracy                   

Optimal k value for minimum error rate: 16
1997
Number of rows in test_data: 200
confusion_matrix:
[[89 20]
 [83  8]]
classification_report
              precision    recall  f1-score   support

          -1       0.52      0.82      0.63       109
           1       0.29      0.09      0.13        91

    accuracy                           0.48       200
   macro avg       0.40      0.45      0.38       200
weighted avg       0.41      0.48      0.41       200

新數據的預測準確率: 0.485
0.7775686785714286
最近鄰居中預測值為1的前5筆索引:
[32, 133, 15, 116, 125]
32      中石化       
133    台紙         
15     旺宏         
116    D 致伸       
125    桂宏         
Name: 簡稱, dtype: object
32    -32.4429
133   -40.7609
15    -29.5095
116   -36.2725
125   -35.0797
Name: Return, dtype: float64
0.6518689999999999
1999
Number of rows in test_data: 200
confusion_matrix:
[[101  10]
 [ 75  14]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.91      0.70       111
   

Optimal k value for minimum error rate: 3
1997
Number of rows in test_data: 200
confusion_matrix:
[[78 31]
 [73 18]]
classification_report
              precision    recall  f1-score   support

          -1       0.52      0.72      0.60       109
           1       0.37      0.20      0.26        91

    accuracy                           0.48       200
   macro avg       0.44      0.46      0.43       200
weighted avg       0.45      0.48      0.44       200

新數據的預測準確率: 0.48
0.7808355102040816
最近鄰居中預測值為1的前5筆索引:
[69, 44, 15, 82, 124]
69      永豐餘       
44     中保         
15     旺宏         
82     冠德         
124    力麗         
Name: 簡稱, dtype: object
69    -27.8824
44    -27.5338
15    -29.5095
82    -35.4419
124   -38.5344
Name: Return, dtype: float64
0.682196
1999
Number of rows in test_data: 200
confusion_matrix:
[[85 26]
 [68 21]]
classification_report
              precision    recall  f1-score   support

          -1       0.56      0.77      0.64       111
           1       0.

Optimal k value for minimum error rate: 1
1997
Number of rows in test_data: 200
confusion_matrix:
[[89 20]
 [52 39]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.82      0.71       109
           1       0.66      0.43      0.52        91

    accuracy                           0.64       200
   macro avg       0.65      0.62      0.62       200
weighted avg       0.64      0.64      0.62       200

新數據的預測準確率: 0.64
0.9403457457627119
最近鄰居中預測值為1的前5筆索引:
[33, 102, 44, 109, 14]
33      統一超       
102    中鼎         
44     中保         
109     楠梓電       
14     裕隆         
Name: 簡稱, dtype: object
33     24.9683
102    22.4832
44    -27.5338
109    62.2231
14      1.1003
Name: Return, dtype: float64
1.1664822
1999
Number of rows in test_data: 200
confusion_matrix:
[[71 40]
 [53 36]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.64      0.60       111
           1       

Optimal k value for minimum error rate: 16
1997
Number of rows in test_data: 200
confusion_matrix:
[[98 11]
 [78 13]]
classification_report
              precision    recall  f1-score   support

          -1       0.56      0.90      0.69       109
           1       0.54      0.14      0.23        91

    accuracy                           0.56       200
   macro avg       0.55      0.52      0.46       200
weighted avg       0.55      0.56      0.48       200

新數據的預測準確率: 0.555
0.840160875
最近鄰居中預測值為1的前5筆索引:
[128, 33, 16, 88, 58]
128    東森         
33      統一超       
16     台泥         
88     中強         
58      統一實       
Name: 簡稱, dtype: object
128   -35.0135
33     24.9683
16    -19.7175
88    -15.2596
58    -25.0199
Name: Return, dtype: float64
0.8599156
1999
Number of rows in test_data: 200
confusion_matrix:
[[91 20]
 [78 11]]
classification_report
              precision    recall  f1-score   support

          -1       0.54      0.82      0.65       111
           1       0.35  

Optimal k value for minimum error rate: 1
1997
Number of rows in test_data: 200
confusion_matrix:
[[80 29]
 [60 31]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.73      0.64       109
           1       0.52      0.34      0.41        91

    accuracy                           0.56       200
   macro avg       0.54      0.54      0.53       200
weighted avg       0.55      0.56      0.54       200

新數據的預測準確率: 0.555
0.8394492833333334
最近鄰居中預測值為1的前5筆索引:
[128, 2, 66, 51, 23]
128    東森         
2      中鋼         
66     大榮         
51     聯強         
23     國建         
Name: 簡稱, dtype: object
128   -35.0135
2      -9.2224
66    -38.3127
51     46.0888
23    -41.5319
Name: Return, dtype: float64
0.8440166
1999
Number of rows in test_data: 200
confusion_matrix:
[[80 31]
 [65 24]]
classification_report
              precision    recall  f1-score   support

          -1       0.55      0.72      0.62       111
           1       0

Optimal k value for minimum error rate: 52
1997
Number of rows in test_data: 200
confusion_matrix:
[[107   2]
 [ 77  14]]
classification_report
              precision    recall  f1-score   support

          -1       0.58      0.98      0.73       109
           1       0.88      0.15      0.26        91

    accuracy                           0.60       200
   macro avg       0.73      0.57      0.50       200
weighted avg       0.72      0.60      0.52       200

新數據的預測準確率: 0.605
1.103316625
最近鄰居中預測值為1的前5筆索引:
[44, 12, 76, 22, 60]
44    中保         
12     英業達       
76    飛瑞         
22    華通         
60    環電         
Name: 簡稱, dtype: object
44   -27.5338
12    42.6763
76     6.8826
22    57.1229
60    -4.7036
Name: Return, dtype: float64
1.1488888
1999
Number of rows in test_data: 200
confusion_matrix:
[[101  10]
 [ 76  13]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.91      0.70       111
           1       0.57     

Optimal k value for minimum error rate: 40
1997
Number of rows in test_data: 200
confusion_matrix:
[[103   6]
 [ 69  22]]
classification_report
              precision    recall  f1-score   support

          -1       0.60      0.94      0.73       109
           1       0.79      0.24      0.37        91

    accuracy                           0.62       200
   macro avg       0.69      0.59      0.55       200
weighted avg       0.68      0.62      0.57       200

新數據的預測準確率: 0.625
1.0152911785714285
最近鄰居中預測值為1的前5筆索引:
[35, 44, 76, 110, 22]
35     陽明         
44     中保         
76     飛瑞         
110    佳格         
22     華通         
Name: 簡稱, dtype: object
35     -3.3784
44    -27.5338
76      6.8826
110    -6.4982
22     57.1229
Name: Return, dtype: float64
1.0531902
1999
Number of rows in test_data: 200
confusion_matrix:
[[99 12]
 [71 18]]
classification_report
              precision    recall  f1-score   support

          -1       0.58      0.89      0.70       111
           1  

Optimal k value for minimum error rate: 8
1997
Number of rows in test_data: 200
confusion_matrix:
[[85 24]
 [79 12]]
classification_report
              precision    recall  f1-score   support

          -1       0.52      0.78      0.62       109
           1       0.33      0.13      0.19        91

    accuracy                           0.48       200
   macro avg       0.43      0.46      0.41       200
weighted avg       0.43      0.48      0.43       200

新數據的預測準確率: 0.485
0.7439703611111111
最近鄰居中預測值為1的前5筆索引:
[32, 16, 81, 82, 90]
32     中石化       
16    台泥         
81    倫飛         
82    冠德         
90     嘉食化       
Name: 簡稱, dtype: object
32   -32.4429
16   -19.7175
81   -11.7489
82   -35.4419
90   -13.4908
Name: Return, dtype: float64
0.774316
1999
Number of rows in test_data: 200
confusion_matrix:
[[91 20]
 [68 21]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.82      0.67       111
           1       0.51      0.

Optimal k value for minimum error rate: 11
1997
Number of rows in test_data: 200
confusion_matrix:
[[98 11]
 [65 26]]
classification_report
              precision    recall  f1-score   support

          -1       0.60      0.90      0.72       109
           1       0.70      0.29      0.41        91

    accuracy                           0.62       200
   macro avg       0.65      0.59      0.56       200
weighted avg       0.65      0.62      0.58       200

新數據的預測準確率: 0.62
0.956794
最近鄰居中預測值為1的前5筆索引:
[0, 42, 44, 14, 86]
0      台積電       
42    正新         
44    中保         
14    裕隆         
86    台橡         
Name: 簡稱, dtype: object
0     -6.3648
42    -8.7819
44   -27.5338
14     1.1003
86   -30.8219
Name: Return, dtype: float64
0.8551958
1999
Number of rows in test_data: 200
confusion_matrix:
[[96 15]
 [74 15]]
classification_report
              precision    recall  f1-score   support

          -1       0.56      0.86      0.68       111
           1       0.50      0.17      0.

Optimal k value for minimum error rate: 8
1997
Number of rows in test_data: 200
confusion_matrix:
[[78 31]
 [72 19]]
classification_report
              precision    recall  f1-score   support

          -1       0.52      0.72      0.60       109
           1       0.38      0.21      0.27        91

    accuracy                           0.48       200
   macro avg       0.45      0.46      0.44       200
weighted avg       0.46      0.48      0.45       200

新數據的預測準確率: 0.485
0.82909324
最近鄰居中預測值為1的前5筆索引:
[32, 72, 15, 93, 30]
32     中石化       
72    凌陽         
15    旺宏         
93    嘉泥         
30    三陽         
Name: 簡稱, dtype: object
32   -32.4429
72    21.4721
15   -29.5095
93   -27.6940
30   -35.3336
Name: Return, dtype: float64
0.7929842
1999
Number of rows in test_data: 200
confusion_matrix:
[[91 20]
 [74 15]]
classification_report
              precision    recall  f1-score   support

          -1       0.55      0.82      0.66       111
           1       0.43      0.17     

Optimal k value for minimum error rate: 1
1997
Number of rows in test_data: 200
confusion_matrix:
[[76 33]
 [62 29]]
classification_report
              precision    recall  f1-score   support

          -1       0.55      0.70      0.62       109
           1       0.47      0.32      0.38        91

    accuracy                           0.53       200
   macro avg       0.51      0.51      0.50       200
weighted avg       0.51      0.53      0.51       200

新數據的預測準確率: 0.525
0.8015478548387096
最近鄰居中預測值為1的前5筆索引:
[70, 7, 44, 16, 124]
70     宏盛         
7      大同         
44     中保         
16     台泥         
124    力麗         
Name: 簡稱, dtype: object
70    -10.8395
7       1.5517
44    -27.5338
16    -19.7175
124   -38.5344
Name: Return, dtype: float64
0.809853
1999
Number of rows in test_data: 200
confusion_matrix:
[[80 31]
 [63 26]]
classification_report
              precision    recall  f1-score   support

          -1       0.56      0.72      0.63       111
           1       0.

Optimal k value for minimum error rate: 11
1997
Number of rows in test_data: 200
confusion_matrix:
[[98 11]
 [67 24]]
classification_report
              precision    recall  f1-score   support

          -1       0.59      0.90      0.72       109
           1       0.69      0.26      0.38        91

    accuracy                           0.61       200
   macro avg       0.64      0.58      0.55       200
weighted avg       0.64      0.61      0.56       200

新數據的預測準確率: 0.61
0.9240956571428571
最近鄰居中預測值為1的前5筆索引:
[0, 76, 14, 92, 94]
0      台積電       
76    飛瑞         
14    裕隆         
92    東聯         
94    德寶         
Name: 簡稱, dtype: object
0     -6.3648
76     6.8826
14     1.1003
92   -29.7543
94   -32.8149
Name: Return, dtype: float64
0.8780978
1999
Number of rows in test_data: 200
confusion_matrix:
[[101  10]
 [ 74  15]]
classification_report
              precision    recall  f1-score   support

          -1       0.58      0.91      0.71       111
           1       0.60    

Optimal k value for minimum error rate: 1
1997
Number of rows in test_data: 200
confusion_matrix:
[[74 35]
 [63 28]]
classification_report
              precision    recall  f1-score   support

          -1       0.54      0.68      0.60       109
           1       0.44      0.31      0.36        91

    accuracy                           0.51       200
   macro avg       0.49      0.49      0.48       200
weighted avg       0.50      0.51      0.49       200

新數據的預測準確率: 0.51
0.8417321904761905
最近鄰居中預測值為1的前5筆索引:
[99, 102, 7, 106, 44]
99     威致         
102    中鼎         
7      大同         
106    裕民         
44     中保         
Name: 簡稱, dtype: object
99    -66.3043
102    22.4832
7       1.5517
106   -26.5082
44    -27.5338
Name: Return, dtype: float64
0.8073772
1999
Number of rows in test_data: 200
confusion_matrix:
[[81 30]
 [61 28]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.73      0.64       111
           1       0

Optimal k value for minimum error rate: 30
1997
Number of rows in test_data: 200
confusion_matrix:
[[101   8]
 [ 86   5]]
classification_report
              precision    recall  f1-score   support

          -1       0.54      0.93      0.68       109
           1       0.38      0.05      0.10        91

    accuracy                           0.53       200
   macro avg       0.46      0.49      0.39       200
weighted avg       0.47      0.53      0.42       200

新數據的預測準確率: 0.53
0.807621923076923
最近鄰居中預測值為1的前5筆索引:
[128, 129, 76, 82, 51]
128    東森         
129    盛餘         
76     飛瑞         
82     冠德         
51     聯強         
Name: 簡稱, dtype: object
128   -35.0135
129   -44.1894
76      6.8826
82    -35.4419
51     46.0888
Name: Return, dtype: float64
0.8766532
1999
Number of rows in test_data: 200
confusion_matrix:
[[107   4]
 [ 83   6]]
classification_report
              precision    recall  f1-score   support

          -1       0.56      0.96      0.71       111
           

Optimal k value for minimum error rate: 49
1997
Number of rows in test_data: 200
confusion_matrix:
[[108   1]
 [ 76  15]]
classification_report
              precision    recall  f1-score   support

          -1       0.59      0.99      0.74       109
           1       0.94      0.16      0.28        91

    accuracy                           0.61       200
   macro avg       0.76      0.58      0.51       200
weighted avg       0.75      0.61      0.53       200

新數據的預測準確率: 0.615
1.1197788124999999
最近鄰居中預測值為1的前5筆索引:
[33, 12, 79, 22, 60]
33     統一超       
12     英業達       
79    旭麗         
22    華通         
60    環電         
Name: 簡稱, dtype: object
33    24.9683
12    42.6763
79    14.0625
22    57.1229
60    -4.7036
Name: Return, dtype: float64
1.2682528
1999
Number of rows in test_data: 200
confusion_matrix:
[[102   9]
 [ 80   9]]
classification_report
              precision    recall  f1-score   support

          -1       0.56      0.92      0.70       111
           1       0.

1.5924136
{1997: 1.1197788124999999, 1999: 0.5924863333333334, 2000: 1.79219625, 2001: 0.8187534642857143, 2002: 1.2344150304347825, 2003: 1.007631009375, 2004: 1.2862168086956522, 2005: 1.3380991555555555, 2006: 1.1172011444444445, 2007: 0.49043890243902444, 2008: 2.0011302972972977}
年均化複利為:0.2077368138986051


{1997: 1.2682528, 1999: 0.40971480000000005, 2000: 1.5313626, 2001: 0.5893746, 2002: 1.17255854, 2003: 0.80808586, 2004: 1.7880766000000001, 2005: 1.3495298, 2006: 0.9448356, 2007: 0.450511, 2008: 1.5924136}
年均化複利為:0.0660757976678254
ori sum2:0.7268337743460793
test years have:11
after sum2:0.0660757976678254
Optimal k value for minimum error rate: 4
1997
Number of rows in test_data: 200
confusion_matrix:
[[97 12]
 [67 24]]
classification_report
              precision    recall  f1-score   support

          -1       0.59      0.89      0.71       109
           1       0.67      0.26      0.38        91

    accuracy                           0.60       200
   macro avg      

Optimal k value for minimum error rate: 6
1997
Number of rows in test_data: 200
confusion_matrix:
[[86 23]
 [73 18]]
classification_report
              precision    recall  f1-score   support

          -1       0.54      0.79      0.64       109
           1       0.44      0.20      0.27        91

    accuracy                           0.52       200
   macro avg       0.49      0.49      0.46       200
weighted avg       0.49      0.52      0.47       200

新數據的預測準確率: 0.52
0.8687800731707317
最近鄰居中預測值為1的前5筆索引:
[2, 37, 16, 51, 125]
2      中鋼         
37     味全         
16     台泥         
51     聯強         
125    桂宏         
Name: 簡稱, dtype: object
2      -9.2224
37    -75.7294
16    -19.7175
51     46.0888
125   -35.0797
Name: Return, dtype: float64
0.8126796
1999
Number of rows in test_data: 200
confusion_matrix:
[[96 15]
 [64 25]]
classification_report
              precision    recall  f1-score   support

          -1       0.60      0.86      0.71       111
           1       0.

Optimal k value for minimum error rate: 1
1997
Number of rows in test_data: 200
confusion_matrix:
[[78 31]
 [65 26]]
classification_report
              precision    recall  f1-score   support

          -1       0.55      0.72      0.62       109
           1       0.46      0.29      0.35        91

    accuracy                           0.52       200
   macro avg       0.50      0.50      0.49       200
weighted avg       0.50      0.52      0.50       200

新數據的預測準確率: 0.52
0.8393678596491229
最近鄰居中預測值為1的前5筆索引:
[44, 76, 119, 27, 93]
44     中保         
76     飛瑞         
119    矽統         
27     國巨         
93     嘉泥         
Name: 簡稱, dtype: object
44    -27.5338
76      6.8826
119    90.8365
27    -21.0055
93    -27.6940
Name: Return, dtype: float64
1.0429716
1999
Number of rows in test_data: 200
confusion_matrix:
[[80 31]
 [59 30]]
classification_report
              precision    recall  f1-score   support

          -1       0.58      0.72      0.64       111
           1       0

Optimal k value for minimum error rate: 7
1997
Number of rows in test_data: 200
confusion_matrix:
[[97 12]
 [63 28]]
classification_report
              precision    recall  f1-score   support

          -1       0.61      0.89      0.72       109
           1       0.70      0.31      0.43        91

    accuracy                           0.62       200
   macro avg       0.65      0.60      0.57       200
weighted avg       0.65      0.62      0.59       200

新數據的預測準確率: 0.625
0.94474715
最近鄰居中預測值為1的前5筆索引:
[0, 7, 74, 14, 26]
0      台積電       
7     大同         
74    國豐         
14    裕隆         
26    矽品         
Name: 簡稱, dtype: object
0     -6.3648
7      1.5517
74   -28.3462
14     1.1003
26     2.0266
Name: Return, dtype: float64
0.9399352
1999
Number of rows in test_data: 200
confusion_matrix:
[[99 12]
 [66 23]]
classification_report
              precision    recall  f1-score   support

          -1       0.60      0.89      0.72       111
           1       0.66      0.26      0

Optimal k value for minimum error rate: 1
1997
Number of rows in test_data: 200
confusion_matrix:
[[80 29]
 [60 31]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.73      0.64       109
           1       0.52      0.34      0.41        91

    accuracy                           0.56       200
   macro avg       0.54      0.54      0.53       200
weighted avg       0.55      0.56      0.54       200

新數據的預測準確率: 0.555
0.8629294166666667
最近鄰居中預測值為1的前5筆索引:
[7, 72, 74, 44, 124]
7      大同         
72     凌陽         
74     國豐         
44     中保         
124    力麗         
Name: 簡稱, dtype: object
7       1.5517
72     21.4721
74    -28.3462
44    -27.5338
124   -38.5344
Name: Return, dtype: float64
0.8572188
1999
Number of rows in test_data: 200
confusion_matrix:
[[81 30]
 [62 27]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.73      0.64       111
           1       0

Optimal k value for minimum error rate: 38
1997
Number of rows in test_data: 200
confusion_matrix:
[[107   2]
 [ 91   0]]
classification_report
              precision    recall  f1-score   support

          -1       0.54      0.98      0.70       109
           1       0.00      0.00      0.00        91

    accuracy                           0.54       200
   macro avg       0.27      0.49      0.35       200
weighted avg       0.29      0.54      0.38       200

新數據的預測準確率: 0.535
0.5163030000000001
最近鄰居中預測值為1的前5筆索引:
[129, 137]
129    盛餘         
137    宏普         
Name: 簡稱, dtype: object
129   -44.1894
137   -52.5500
Name: Return, dtype: float64
0.5163030000000001
1999
Number of rows in test_data: 200
confusion_matrix:
[[110   1]
 [ 87   2]]
classification_report
              precision    recall  f1-score   support

          -1       0.56      0.99      0.71       111
           1       0.67      0.02      0.04        89

    accuracy                           0.56       200
   ma

confusion_matrix:
[[86 25]
 [64 25]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.77      0.66       111
           1       0.50      0.28      0.36        89

    accuracy                           0.56       200
   macro avg       0.54      0.53      0.51       200
weighted avg       0.54      0.56      0.53       200

新數據的預測準確率: 0.555
0.56720594
最近鄰居中預測值為1的前5筆索引:
[99, 69, 44, 15, 25]
499    宏盛         
469    年興         
444    中華         
415    仁寶         
425    聯強         
Name: 簡稱, dtype: object
499   -65.6894
469   -34.9908
444    18.7081
415   -43.0396
425   -70.0025
Name: Return, dtype: float64
0.6099716
2000
Number of rows in test_data: 200
confusion_matrix:
[[89 38]
 [43 30]]
classification_report
              precision    recall  f1-score   support

          -1       0.67      0.70      0.69       127
           1       0.44      0.41      0.43        73

    accuracy                           0.59       200

confusion_matrix:
[[87 24]
 [66 23]]
classification_report
              precision    recall  f1-score   support

          -1       0.57      0.78      0.66       111
           1       0.49      0.26      0.34        89

    accuracy                           0.55       200
   macro avg       0.53      0.52      0.50       200
weighted avg       0.53      0.55      0.52       200

新數據的預測準確率: 0.55
0.581361659574468
最近鄰居中預測值為1的前5筆索引:
[2, 44, 87, 26, 124]
402    華碩         
444    中華         
487    致茂         
426     統一超       
524    和泰         
Name: 簡稱, dtype: object
402   -59.6516
444    18.7081
487   -66.7308
426   -22.9665
524    11.1742
Name: Return, dtype: float64
0.7610667999999999
2000
Number of rows in test_data: 200
confusion_matrix:
[[91 36]
 [46 27]]
classification_report
              precision    recall  f1-score   support

          -1       0.66      0.72      0.69       127
           1       0.43      0.37      0.40        73

    accuracy                          

              precision    recall  f1-score   support

          -1       0.58      0.75      0.65       111
           1       0.50      0.31      0.39        89

    accuracy                           0.56       200
   macro avg       0.54      0.53      0.52       200
weighted avg       0.54      0.56      0.53       200

新數據的預測準確率: 0.555
0.5678945357142857
最近鄰居中預測值為1的前5筆索引:
[64, 69, 44, 15, 124]
464    正新         
469    年興         
444    中華         
415    仁寶         
524    和泰         
Name: 簡稱, dtype: object
464   -13.8482
469   -34.9908
444    18.7081
415   -43.0396
524    11.1742
Name: Return, dtype: float64
0.8760074
2000
Number of rows in test_data: 200
confusion_matrix:
[[88 39]
 [44 29]]
classification_report
              precision    recall  f1-score   support

          -1       0.67      0.69      0.68       127
           1       0.43      0.40      0.41        73

    accuracy                           0.58       200
   macro avg       0.55      0.55      0.55      

confusion_matrix:
[[56 70]
 [34 40]]
classification_report
              precision    recall  f1-score   support

          -1       0.62      0.44      0.52       126
           1       0.36      0.54      0.43        74

    accuracy                           0.48       200
   macro avg       0.49      0.49      0.48       200
weighted avg       0.53      0.48      0.49       200

新數據的預測準確率: 0.48
1.0754623181818181
最近鄰居中預測值為1的前5筆索引:
[134, 71, 11, 43, 63]
334    正隆         
271    燿華         
211    仁寶         
243    正新         
263     統一實       
Name: 簡稱, dtype: object
334     4.6178
271   -24.7732
211    39.4893
243   -22.2567
263   -32.4153
Name: Return, dtype: float64
0.9293238
2000
Number of rows in test_data: 200
confusion_matrix:
[[56 71]
 [32 41]]
classification_report
              precision    recall  f1-score   support

          -1       0.64      0.44      0.52       127
           1       0.37      0.56      0.44        73

    accuracy                           0.48  

confusion_matrix:
[[74 52]
 [40 34]]
classification_report
              precision    recall  f1-score   support

          -1       0.65      0.59      0.62       126
           1       0.40      0.46      0.42        74

    accuracy                           0.54       200
   macro avg       0.52      0.52      0.52       200
weighted avg       0.56      0.54      0.55       200

新數據的預測準確率: 0.54
1.1676358604651162
最近鄰居中預測值為1的前5筆索引:
[99, 102, 11, 45, 120]
299     三商行       
302    D 復盛       
211    仁寶         
245    聲寶         
320    智邦         
Name: 簡稱, dtype: object
299     10.7232
302    -24.7892
211     39.4893
245    -54.4665
320    153.0937
Name: Return, dtype: float64
1.248101
2000
Number of rows in test_data: 200
confusion_matrix:
[[65 62]
 [32 41]]
classification_report
              precision    recall  f1-score   support

          -1       0.67      0.51      0.58       127
           1       0.40      0.56      0.47        73

    accuracy                           0

              precision    recall  f1-score   support

          -1       0.67      0.57      0.62       126
           1       0.41      0.51      0.46        74

    accuracy                           0.55       200
   macro avg       0.54      0.54      0.54       200
weighted avg       0.57      0.55      0.56       200

新數據的預測準確率: 0.55
1.203771097826087
最近鄰居中預測值為1的前5筆索引:
[5, 134, 71, 47, 94]
205    鴻海         
334    正隆         
271    燿華         
247    台鳳         
294    國豐         
Name: 簡稱, dtype: object
205    87.7049
334     4.6178
271   -24.7732
247   -54.5685
294   -64.0000
Name: Return, dtype: float64
0.8979619999999999
2000
Number of rows in test_data: 200
confusion_matrix:
[[58 69]
 [36 37]]
classification_report
              precision    recall  f1-score   support

          -1       0.62      0.46      0.52       127
           1       0.35      0.51      0.41        73

    accuracy                           0.48       200
   macro avg       0.48      0.48      0.47

confusion_matrix:
[[70 56]
 [40 34]]
classification_report
              precision    recall  f1-score   support

          -1       0.64      0.56      0.59       126
           1       0.38      0.46      0.41        74

    accuracy                           0.52       200
   macro avg       0.51      0.51      0.50       200
weighted avg       0.54      0.52      0.53       200

新數據的預測準確率: 0.52
1.1088586777777778
最近鄰居中預測值為1的前5筆索引:
[130, 6, 135, 51, 93]
330    永記         
206     英業達       
335    敬鵬         
251    矽統         
293    台苯         
Name: 簡稱, dtype: object
330    -25.5993
206    -13.1390
335     -2.5884
251    154.6171
293     49.2027
Name: Return, dtype: float64
1.3249862000000001
2000
Number of rows in test_data: 200
confusion_matrix:
[[61 66]
 [40 33]]
classification_report
              precision    recall  f1-score   support

          -1       0.60      0.48      0.54       127
           1       0.33      0.45      0.38        73

    accuracy                   

confusion_matrix:
[[72 54]
 [42 32]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.57      0.60       126
           1       0.37      0.43      0.40        74

    accuracy                           0.52       200
   macro avg       0.50      0.50      0.50       200
weighted avg       0.54      0.52      0.53       200

新數據的預測準確率: 0.52
1.1488917441860464
最近鄰居中預測值為1的前5筆索引:
[128, 37, 116, 52, 125]
328    瑞昱         
237    華新         
316    誠洲         
252    友訊         
325    精英         
Name: 簡稱, dtype: object
328    113.0053
237     48.0952
316    -42.9235
252      2.0018
325     80.1532
Name: Return, dtype: float64
1.400664
2000
Number of rows in test_data: 200
confusion_matrix:
[[66 61]
 [38 35]]
classification_report
              precision    recall  f1-score   support

          -1       0.63      0.52      0.57       127
           1       0.36      0.48      0.41        73

    accuracy                           

confusion_matrix:
[[64 62]
 [35 39]]
classification_report
              precision    recall  f1-score   support

          -1       0.65      0.51      0.57       126
           1       0.39      0.53      0.45        74

    accuracy                           0.52       200
   macro avg       0.52      0.52      0.51       200
weighted avg       0.55      0.52      0.52       200

新數據的預測準確率: 0.515
1.1339807326732674
最近鄰居中預測值為1的前5筆索引:
[37, 9, 74, 78, 113]
237    華新         
209    宏電         
274    中工         
278    新纖         
313    台橡         
Name: 簡稱, dtype: object
237     48.0952
209    191.3663
274    -37.7753
278    -20.4785
313    -40.3740
Name: Return, dtype: float64
1.2816674
2000
Number of rows in test_data: 200
confusion_matrix:
[[44 83]
 [19 54]]
classification_report
              precision    recall  f1-score   support

          -1       0.70      0.35      0.46       127
           1       0.39      0.74      0.51        73

    accuracy                           0

confusion_matrix:
[[59 67]
 [22 52]]
classification_report
              precision    recall  f1-score   support

          -1       0.73      0.47      0.57       126
           1       0.44      0.70      0.54        74

    accuracy                           0.56       200
   macro avg       0.58      0.59      0.55       200
weighted avg       0.62      0.56      0.56       200

新數據的預測準確率: 0.555
1.1906427226890757
最近鄰居中預測值為1的前5筆索引:
[1, 99, 11, 52, 26]
201    華碩         
299     三商行       
211    仁寶         
252    友訊         
226     統一超       
Name: 簡稱, dtype: object
201    56.0181
299    10.7232
211    39.4893
252     2.0018
226    62.5085
Name: Return, dtype: float64
1.3414818
2000
Number of rows in test_data: 200
confusion_matrix:
[[43 84]
 [17 56]]
classification_report
              precision    recall  f1-score   support

          -1       0.72      0.34      0.46       127
           1       0.40      0.77      0.53        73

    accuracy                           0.49   